Repository onuralpszr/yuko, pull requests merged in 2023-12, with the labels that each got.

#24 feat(hashes): 🚀 md5,sha1,sha224,sha256,sha512 validators and tests are added.
  src/hashes_valid.rs
  src/lib.rs
  tests/test_hash.py
Labels: enhancement, api:validator:rust, api:validator:pytest, api:python

#23 feat(mac_address): ✨ add mac_address validator
  README.md
  src/lib.rs
  src/mac_address_valid.rs
  tests/test_mac_address.py
Labels: documentation, enhancement, api:validator:rust, api:validator:pytest, api:python

#21 feat(domain): add domain validator
  README.md
  src/domain_valid.rs
  src/lib.rs
  tests/test_domain.py
Labels: enhancement, api:validator:rust, api:validator:pytest, api:python

#25 docs: 📝 codefactor badge added
  README.md
Labels: documentation

#26 ci(security): 👷 rustsec audit check added
  .github/workflows/rust-security-audit.yml
Labels: api:security, api:security:rust

#27 doc(readme): update readme file for hash validators)
  README.md
Labels: documentation, good first issue

#28 feat(url): add url validation
  README.md
  src/lib.rs
  src/url_valid.rs
  tests/test_url.py
Labels: api:validator:rust, api:python

#31 feat(logo): add logo for project
  README.md
  logo/validx_logo.png
Labels: enhancement

#32 feat(readme): change project name in readme file
  README.md
  logo/yuko_logo.png
Labels: documentation

#33 feat: 🚀 project renamed to yuko
  .devcontainer/devcontainer.json
  .github/workflows/Coverage-CI.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cliff.toml
  poetry.lock
  pyproject.toml
  python/validx/__init__.py
  python/yuko/__init__.py
  python/yuko/py.typed
  python/yuko/yuko.pyi
  src/lib.rs
  tests/test_country_code.py
  tests/test_domain.py
  tests/test_email.py
  tests/test_hash.py
  tests/test_ip_address.py
  tests/test_mac_address.py
  tests/test_url.py
Labels: enhancement, api:python

#44 docs: 📝 readme badges,logo size,cliff configs
  Cargo.lock
  Cargo.toml
  README.md
  cliff.toml
  logo/yuko_logo.png
  pyproject.toml
Labels: documentation
