Repository onuralpszr/yuko, pull requests merged in 2023-11, with the labels that each got.

#6 feat(email): Implemented an email validator in Rust
  Cargo.lock
  Cargo.toml
  src/email_valid.rs
  src/lib.rs
Labels: enhancement, api:validatior:rust

#10 ci(pre-commit): 👷 initial pre-commit
  .devcontainer/devcontainer.json
  .devcontainer/post_create.sh
  .gitignore
  .pre-commit-config.yaml
  Cargo.toml
  clippy.toml
  deny.toml
  pyproject.toml
  python/validX/__init__.py
  python/validx/__init__.py
  python/validx/py.typed
  python/validx/validx.pyi
  src/country_code_valid.rs
Labels: documentation, enhancement, pre-commit

#9 doc(readme): add readme file
  README.md
Labels: documentation

#11 docs: pre-commit and ci badges added.
  README.md
Labels: documentation, enhancement

#12 fix(import): 🐞 import fix for validx.[any imports access]
  python/validx/__init__.py
Labels: bug

#13 feat(poetry): 🏗️ introduce poetry for dev only setup added
  poetry.lock
  pyproject.toml
Labels: enhancement

#15 feat(test): 🧪 initial python tests are added
  tests/__init__.py
  tests/test_country_code.py
  tests/test_email.py
Labels: enhancement, api:validator:pytest, api:python

#18 ci(coverage): 👷 code-coverage ci and codecov ci addded
  .github/workflows/CI.yml
  .github/workflows/Coverage-CI.yml
  .gitignore
  poetry.lock
  pyproject.toml
  src/country_code_valid.rs
Labels: api:validator:rust, api:validator:pytest, api:python, codecov
